version: '3'

services:
  app:
    build:
      context: .
    restart: always
    container_name: csv-validator
    working_dir: /usr/src/myapp
    ports:
      - "8090:8090"
    volumes:
      - /volume/car:/usr/src/myapp/folder_car
      - /volume/train:/usr/src/myapp/folder_train